import { useState } from "react";
import { Save, Plus, Trash2, Printer, ChevronDown } from "lucide-react";

export function DocumentShell({ eyebrow, title, subtitle, code, status, actions, children, aside }) {
  return <div className="py-5 sm:py-7">
    <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">{eyebrow}</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">{title}</h1>{subtitle && <p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div>
      <div className="flex flex-wrap gap-2 print:hidden">{actions}</div>
    </div>
    <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm print:rounded-none print:border-0 print:shadow-none">
      <header className="border-b-2 border-slate-900 px-5 py-5 sm:px-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">{code || "VividOpt record"}</div><h2 className="mt-1 text-lg font-bold text-slate-900">{title}</h2></div>{status && <span className="inline-flex w-fit rounded-full border border-slate-300 bg-slate-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-600">{status}</span>}</div></header>
      <div className={aside ? "grid lg:grid-cols-[minmax(0,1fr)_280px]" : ""}><div>{children}</div>{aside && <aside className="border-l border-slate-200 bg-slate-50/70 p-5 sm:p-7">{aside}</aside>}</div>
      <footer className="border-t-2 border-slate-900 bg-slate-50 px-5 py-4 text-xs text-slate-400 sm:px-8">VividOpt · Practice Management</footer>
    </article>
  </div>;
}

export function Section({ number, title, description, children }) { return <section className="border-b border-slate-200 p-5 sm:p-7 last:border-b-0"><div className="mb-5 flex items-start gap-3"><span className="pt-0.5 text-[10px] font-bold tracking-widest text-slate-400">{number}</span><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-slate-800">{title}</h3>{description && <p className="mt-1 text-xs text-slate-400">{description}</p>}</div></div>{children}</section>; }

export function Field({ label, value, onChange, type="text", placeholder, options, className="", disabled=false }) { return <label className={`block ${className}`}><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</span>{options ? <select value={value ?? ""} onChange={e=>onChange?.(e.target.value)} disabled={disabled} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-slate-500 disabled:bg-slate-50">{options.map(o=><option key={o.value ?? o} value={o.value ?? o}>{o.label ?? o}</option>)}</select> : type === "textarea" ? <textarea value={value ?? ""} onChange={e=>onChange?.(e.target.value)} placeholder={placeholder} disabled={disabled} rows={4} className="mt-1.5 w-full resize-y rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-slate-500 disabled:bg-slate-50"/> : <input type={type} value={value ?? ""} onChange={e=>onChange?.(e.target.value)} placeholder={placeholder} disabled={disabled} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-slate-500 disabled:bg-slate-50"/>}</label>; }

export function InfoGrid({ items }) { return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{items.map((x,i)=><div key={i}><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{x.label}</div><div className="mt-1 text-sm font-semibold text-slate-700">{x.value || "—"}</div></div>)}</div>; }

export function Table({ columns, rows, empty="No records found." }) { return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-[10px] uppercase tracking-wider text-slate-400">{columns.map(c=><th key={c.key} className={`pb-3 pr-4 ${c.align === "right" ? "text-right" : ""}`}>{c.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r,i)=><tr key={r.id || i} className="border-b border-slate-100 last:border-0">{columns.map(c=><td key={c.key} className={`py-3 pr-4 ${c.align === "right" ? "text-right" : ""}`}>{c.render ? c.render(r) : r[c.key]}</td>)}</tr>) : <tr><td colSpan={columns.length} className="py-10 text-center text-xs text-slate-400">{empty}</td></tr>}</tbody></table></div>; }

export function ActionBar({ onSave, onPrint, saveLabel="Save" }) { return <div className="flex flex-wrap gap-2"><button onClick={onSave} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-semibold text-white hover:bg-slate-800"><Save size={14}/>{saveLabel}</button>{onPrint && <button onClick={onPrint} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-slate-600"><Printer size={14}/>Print</button>}</div>; }

export function RepeatableRows({ rows, setRows, fields }) { return <div className="space-y-3">{rows.map((row,index)=><div key={index} className="rounded-xl border border-slate-200 p-3"><div className="grid gap-3 md:grid-cols-4">{fields.map(f=><Field key={f.key} label={f.label} value={row[f.key]} onChange={v=>setRows(rows.map((r,i)=>i===index?{...r,[f.key]:v}:r))} options={f.options} />)}<button type="button" onClick={()=>setRows(rows.filter((_,i)=>i!==index))} className="mt-5 inline-flex h-10 items-center justify-center rounded-xl border border-red-100 text-red-500 hover:bg-red-50"><Trash2 size={15}/></button></div></div>)}<button type="button" onClick={()=>setRows([...rows,Object.fromEntries(fields.map(f=>[f.key,""]))])} className="inline-flex items-center gap-2 rounded-xl border border-dashed border-slate-300 px-3 py-2 text-xs font-semibold text-slate-600"><Plus size={14}/> Add row</button></div>; }

export function Tabs({ items, active, setActive }) { return <div className="flex gap-1 overflow-x-auto border-b border-slate-200">{items.map(x=><button key={x} onClick={()=>setActive(x)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-xs font-semibold ${active===x?"border-slate-900 text-slate-900":"border-transparent text-slate-400 hover:text-slate-700"}`}>{x}</button>)}</div>; }
