import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),

  organization_admin: Object.values(PERMISSIONS),

  branch_manager: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.ORGANIZATION_VIEW,

    PERMISSIONS.BRANCH_VIEW,

    PERMISSIONS.USER_VIEW,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.CLINICAL_VIEW,

    PERMISSIONS.PRESCRIPTION_VIEW,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.REFUND_CREATE,
  ],

  optometrist: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.CLINICAL_CREATE,
    PERMISSIONS.CLINICAL_UPDATE,

    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.BILLING_VIEW,
  ],

  doctor: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.CLINICAL_CREATE,
    PERMISSIONS.CLINICAL_UPDATE,

    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,
    PERMISSIONS.BILLING_VIEW,
  ],

  sales_executive: [
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.BILLING_VIEW,
  ],

  cashier: [
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,

    PERMISSIONS.PATIENT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,

    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.REFUND_CREATE,

    PERMISSIONS.REPORT_VIEW,
  ],

  inventory_manager: [
    PERMISSIONS.APPOINTMENT_VIEW,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
  ],

  lab_technician: [
    PERMISSIONS.APPOINTMENT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
  ],

  receptionist: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,
  ],
};