import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  // ============================================================
  // SUPER ADMIN
  // ============================================================

  super_admin: Object.values(PERMISSIONS),

  // ============================================================
  // ORGANIZATION ADMIN
  // ============================================================

  organization_admin: [
    // Organization
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_UPDATE,

    // Branches
    PERMISSIONS.BRANCH_VIEW,
    PERMISSIONS.BRANCH_CREATE,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.BRANCH_DELETE,

    // Staff
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,

    // Patients
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_DELETE,

    // Appointments
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    // Clinical
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.CLINICAL_CREATE,
    PERMISSIONS.CLINICAL_UPDATE,

    // Prescriptions
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,

    // Optical
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,

    // Inventory
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,

    // Billing
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,

    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.REFUND_CREATE,

    // Recall
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,

    // Communication
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    // Reports
    PERMISSIONS.REPORT_VIEW,

    // Audit
    PERMISSIONS.AUDIT_VIEW,
  ],

  // ============================================================
  // BRANCH MANAGER
  // ============================================================

  branch_manager: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,

    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    PERMISSIONS.ORGANIZATION_VIEW,

    PERMISSIONS.BRANCH_VIEW,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.CLINICAL_VIEW,

    PERMISSIONS.PRESCRIPTION_VIEW,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,

    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.REFUND_CREATE,
  ],

  // ============================================================
  // OPTOMETRIST
  // ============================================================

  optometrist: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,

    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.CLINICAL_CREATE,
    PERMISSIONS.CLINICAL_UPDATE,

    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,

    PERMISSIONS.ORDER_VIEW,

    PERMISSIONS.BILLING_VIEW,
  ],

  // ============================================================
  // DOCTOR
  // ============================================================

  doctor: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,

    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.CLINICAL_CREATE,
    PERMISSIONS.CLINICAL_UPDATE,

    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,

    PERMISSIONS.BILLING_VIEW,
  ],

  // ============================================================
  // SALES EXECUTIVE
  // ============================================================

  sales_executive: [
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,

    PERMISSIONS.BILLING_VIEW,
  ],

  // ============================================================
  // CASHIER
  // ============================================================

  cashier: [
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    PERMISSIONS.APPOINTMENT_VIEW,

    PERMISSIONS.PATIENT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,

    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,

    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.REFUND_CREATE,

    PERMISSIONS.REPORT_VIEW,
  ],

  // ============================================================
  // INVENTORY MANAGER
  // ============================================================

  inventory_manager: [
    PERMISSIONS.APPOINTMENT_VIEW,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
  ],

  // ============================================================
  // LAB TECHNICIAN
  // ============================================================

  lab_technician: [
    PERMISSIONS.APPOINTMENT_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
  ],

  // ============================================================
  // RECEPTIONIST
  // ============================================================

  receptionist: [
    PERMISSIONS.RECALL_VIEW,
    PERMISSIONS.RECALL_CREATE,
    PERMISSIONS.RECALL_UPDATE,

    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,

    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,

    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,
  ],
};