import {useEffect,useMemo,useState} from "react";
import {Plus,Search,RefreshCw} from "lucide-react";
import {useNavigate} from "react-router-dom";
import {getContactLenses} from "../contactLens.api";
import {DocumentShell,Section,Table} from "../../../components/common/DocumentUI";
const name=p=>[p?.firstName,p?.middleName,p?.lastName].filter(Boolean).join(" ");
const statuses=["draft","ordered","ready","notified","collected","cancelled"];
export default function ContactLensPage(){const nav=useNavigate();const[rows,setRows]=useState([]);const[q,setQ]=useState("");const[status,setStatus]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=async()=>{setLoading(true);try{const r=await getContactLenses(status?{status}:{});setRows(r?.data||[])}catch(e){setError(e?.response?.data?.message||"Unable to load contact lens orders")}finally{setLoading(false)}};useEffect(()=>{load()},[status]);const filtered=useMemo(()=>rows.filter(x=>`${x.orderNumber} ${name(x.patientId)} ${x.patientId?.patientNumber} ${x.brand} ${x.model}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);return <DocumentShell eyebrow="Optical workspace" title="Contact Lens Management" subtitle="Complete contact lens order register and patient workflow." code="CONTACT LENS" actions={<><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold"><RefreshCw size={14}/>Refresh</button><button onClick={()=>nav("/optical/contact-lenses/new")} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3.5 py-2.5 text-xs font-semibold text-white"><Plus size={14}/>New order</button></>}>
{error&&<div className="m-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
<Section number="01" title="Order register"><div className="mb-5 grid gap-3 md:grid-cols-[1fr_180px]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search order, patient, brand or model..." className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-4 text-sm outline-none focus:bg-white"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>{loading?<div className="py-12 text-center text-sm text-slate-400">Loading...</div>:<Table columns={[{key:"order",label:"Order",render:r=><button onClick={()=>nav(`/optical/contact-lenses/${r._id}`)} className="font-semibold text-slate-900 hover:underline">{r.orderNumber}</button>},{key:"patient",label:"Patient",render:r=><button onClick={()=>nav(`/patients/${r.patientId?._id}`)} className="text-left"><span className="font-semibold text-slate-800">{name(r.patientId)}</span><span className="ml-2 text-[10px] text-slate-400">{r.patientId?.patientNumber}</span></button>},{key:"type",label:"Type",render:r=>r.orderType?.replaceAll("_"," ")},{key:"lens",label:"Lens",render:r=>`${r.brand||"—"} ${r.model||""}`},{key:"qty",label:"Qty",render:r=>r.quantity},{key:"total",label:"Total",render:r=>`₹${Number(r.total||0).toFixed(2)}`},{key:"status",label:"Status",render:r=><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold uppercase">{r.status}</span>}]} rows={filtered} empty="No contact lens orders found."/>}</Section>
<Section number="02" title="Workflow summary"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{statuses.map(s=><div key={s} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{s}</div><div className="mt-2 text-2xl font-bold">{rows.filter(r=>r.status===s).length}</div></div>)}</div></Section></DocumentShell>}
