import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, PackageCheck, RefreshCw, Search, Truck, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { DocumentShell, Section, Table } from "../../../components/common/DocumentUI";
import { getDispensingList, updateDispensing } from "../dispensing.api";
const statuses=["ordered","not_ready","ready","notified","collected","cancelled"];
const label=s=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const patientName=p=>[p?.firstName,p?.middleName,p?.lastName].filter(Boolean).join(" ")||"Unknown patient";
const next={ordered:"not_ready",not_ready:"ready",ready:"notified",notified:"collected"};
export default function DispensingPage(){
 const nav=useNavigate(),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await getDispensingList(status?{status}:{});setRows(r?.data||[])}catch(e){setError(e?.response?.data?.message||"Unable to load dispensing jobs")}finally{setLoading(false)}};
 useEffect(()=>{load()},[status]);
 const filtered=useMemo(()=>{const q=query.toLowerCase();return rows.filter(r=>!q||[r.recordNumber,patientName(r.patientId),r.patientId?.patientNumber,r.patientId?.phone,r.brand,r.model,r.itemType].filter(Boolean).join(" ").toLowerCase().includes(q))},[rows,query]);
 const advance=async(r)=>{const target=next[r.status];if(!target)return;try{const x=await updateDispensing(r._id,target);setRows(rs=>rs.map(v=>v._id===r._id?x.data:v))}catch(e){setError(e?.response?.data?.message||"Unable to update status")}};
 const counts=Object.fromEntries(statuses.map(s=>[s,rows.filter(r=>r.status===s).length]));
 return <DocumentShell eyebrow="Optical operations" title="Dispensing" subtitle="One register for spectacle and contact-lens jobs from order through collection." code="DISPENSING" actions={<button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold text-slate-600"><RefreshCw size={14}/>Refresh</button>}>
  {error&&<div className="m-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <Section number="01" title="Workflow overview"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{statuses.map(s=><button key={s} onClick={()=>setStatus(status===s?"":s)} className={`rounded-xl border p-4 text-left transition ${status===s?"border-slate-900 bg-slate-900 text-white":"border-slate-200 bg-slate-50 hover:border-slate-300"}`}><div className={`text-[10px] font-bold uppercase tracking-wider ${status===s?"text-slate-300":"text-slate-400"}`}>{label(s)}</div><div className="mt-2 text-2xl font-bold">{counts[s]||0}</div></button>)}</div></Section>
  <Section number="02" title="Dispensing register" description="Spectacle and contact-lens jobs are managed together. Select a patient to open the patient record."><div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search job, patient, phone, brand or model..." className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-4 text-sm outline-none focus:bg-white"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>
   {loading?<div className="py-12 text-center text-sm text-slate-400">Loading dispensing jobs...</div>:<Table columns={[{key:"record",label:"Job",render:r=><button onClick={()=>nav(`/dispensing/${r._id}`)} className="font-semibold text-slate-900 hover:underline">{r.recordNumber}</button>},{key:"type",label:"Type",render:r=><span className="inline-flex items-center gap-1.5"><PackageCheck size={13} className="text-slate-400"/>{r.itemType}</span>},{key:"patient",label:"Patient",render:r=><button onClick={()=>nav(`/patients/${r.patientId?._id}`)} className="text-left"><span className="block font-semibold text-slate-800 hover:underline">{patientName(r.patientId)}</span><span className="text-[10px] text-slate-400">{r.patientId?.patientNumber} · {r.patientId?.phone||"No phone"}</span></button>},{key:"dueDate",label:"Due",render:r=>r.dueDate?new Date(r.dueDate).toLocaleDateString("en-IN"):"—"},{key:"status",label:"Status",render:r=><span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider">{label(r.status)}</span>},{key:"action",label:"Next",render:r=>next[r.status]?<button onClick={()=>advance(r)} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-2.5 py-1.5 text-[10px] font-bold text-white"><CheckCircle2 size={12}/>{label(next[r.status])}</button>:<span className="text-xs text-slate-400">—</span>}]} rows={filtered} empty="No dispensing jobs found."/>}</Section>
  <Section number="03" title="Operational stages"><div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="rounded-lg border px-3 py-2">Ordered</span><span>→</span><span className="rounded-lg border px-3 py-2">Not Ready</span><span>→</span><span className="rounded-lg border px-3 py-2">Ready</span><span>→</span><span className="rounded-lg border px-3 py-2">Notified</span><span>→</span><span className="rounded-lg border px-3 py-2">Collected</span></div></Section>
 </DocumentShell>
}
