import { useEffect,useState } from "react";
import { ArrowLeft, CheckCircle2, Phone, Printer, UserRound } from "lucide-react";
import { useNavigate,useParams } from "react-router-dom";
import { DocumentShell, Section, Field, InfoGrid } from "../../../components/common/DocumentUI";
import { getDispensing, updateDispensing } from "../dispensing.api";
const next={ordered:"not_ready",not_ready:"ready",ready:"notified",notified:"collected"};
const label=s=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const patientName=p=>[p?.firstName,p?.middleName,p?.lastName].filter(Boolean).join(" ");
export default function DispensingDetailsPage(){const {id}=useParams(),nav=useNavigate();const[d,setD]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const r=await getDispensing(id);setD(r?.data)}catch(e){setError(e?.response?.data?.message||"Unable to load job")}finally{setLoading(false)}};useEffect(()=>{load()},[id]);
 const advance=async()=>{if(!d||!next[d.status])return;try{const r=await updateDispensing(id,next[d.status]);setD(r.data)}catch(e){setError(e?.response?.data?.message||"Unable to update status")}};
 if(loading)return <div className="py-12 text-center text-sm text-slate-400">Loading...</div>;if(error)return <div className="py-8 text-sm text-red-600">{error}</div>;if(!d)return null;const p=d.patientId;
 return <DocumentShell eyebrow="Dispensing record" title={d.recordNumber} subtitle={`${d.itemType} · ${patientName(p)}`} code="DISPENSING" status={label(d.status)} actions={<><button onClick={()=>nav(-1)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold text-slate-600"><ArrowLeft size={14}/>Back</button>{next[d.status]&&<button onClick={advance} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3.5 py-2.5 text-xs font-semibold text-white"><CheckCircle2 size={14}/>{label(next[d.status])}</button>}<button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold text-slate-600"><Printer size={14}/>Print</button></>}>
  <Section number="01" title="Patient"><InfoGrid items={[{label:"Patient",value:patientName(p)},{label:"Patient number",value:p?.patientNumber},{label:"Date of birth",value:p?.dob?new Date(p.dob).toLocaleDateString("en-IN"):"—"},{label:"Phone",value:p?.phone||"—"}]}/><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>nav(`/patients/${p?._id}`)} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3.5 py-2.5 text-xs font-semibold text-white"><UserRound size={14}/>Open patient record</button>{p?.phone&&<a href={`tel:${p.phone}`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3.5 py-2.5 text-xs font-semibold text-slate-600"><Phone size={14}/>Call patient</a>}</div></Section>
  <Section number="02" title="Job information"><InfoGrid items={[{label:"Type",value:d.itemType},{label:"Job / order number",value:d.recordNumber},{label:"Order date",value:d.orderDate||d.jobDate?new Date(d.orderDate||d.jobDate).toLocaleDateString("en-IN"):"—"},{label:"Due date",value:d.dueDate?new Date(d.dueDate).toLocaleDateString("en-IN"):"—"}]}/></Section>
  <Section number="03" title={d.itemType==="Spectacle"?"Spectacle details":"Contact lens details"}>{d.itemType==="Spectacle"?<><InfoGrid items={[{label:"Frame",value:d.frame?.description||d.frame?.code},{label:"Frame code",value:d.frame?.code},{label:"Lens",value:d.lens?.description||d.lens?.code},{label:"Lens supplier",value:d.lens?.supplier}]}/><div className="mt-6 grid gap-4 md:grid-cols-3"><Field label="Frame price" value={d.frame?.price??0} disabled/><Field label="Lens price" value={d.lens?.price??0} disabled/><Field label="Discount" value={d.discount??0} disabled/></div></>:<><InfoGrid items={[{label:"Lens type",value:d.lensType},{label:"Brand",value:d.brand},{label:"Model",value:d.model},{label:"Supplier",value:d.supplier},{label:"Replacement",value:d.replacement},{label:"Quantity",value:d.quantity}]}/></>}</Section>
  <Section number="04" title="Workflow"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[{l:"Ordered",v:d.orderDate||d.jobDate},{l:"Ready",v:d.jobReadyAt},{l:"Last notified",v:d.lastNotifiedAt},{l:"Collected",v:d.collectedAt},{l:"Notifications",v:d.notificationCount??0}].map(x=><div key={x.l} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{x.l}</div><div className="mt-2 text-sm font-semibold text-slate-700">{typeof x.v==="number"?x.v:x.v?new Date(x.v).toLocaleDateString("en-IN"):"Pending"}</div></div>)}</div></Section>
  <Section number="05" title="Notes"><div className="whitespace-pre-wrap rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-600">{d.notes||"No dispensing notes recorded."}</div></Section>
 </DocumentShell>}
